// Generated by CoffeeScript 1.10.0
(function() {
  (function(root, factory) {
    if (typeof define === 'function' && define.amd) {
      return define(['elgg', 'jquery', 'foowdCookiePolicy'], factory);
    } else if (typeof exports === 'object') {
      return module.exports = factory();
    } else {
      return root.returnExports = factory();
    }
  })(this, function() {
    var $, elgg, policy;
    $ = require('jquery');
    elgg = require('elgg');
    policy = require('foowdCookiePolicy');
    policy.init({
      link: elgg.get_site_url() + 'cookie-policy'
    });
    $('.elgg-system-messages li.elgg-message').finish().fadeIn(0).delay(3000).fadeOut(4000);
  });

}).call(this);
