// Generated by CoffeeScript 1.10.0
(function() {
  var root;

  root = this;

  (function(root, factory) {
    if (typeof define === 'function' && define.amd) {
      return define(['elgg', 'jquery', 'foowdCookiePolicy', 'page'], factory);
    } else if (typeof exports === 'object') {
      return module.exports = factory();
    } else {
      return root.returnExports = factory();
    }
  })(this, function() {
    var $, elgg, navbar, navbarBottom, page, policy;
    $ = require('jquery');
    elgg = require('elgg');
    page = require('page');
    policy = require('foowdCookiePolicy');
    policy.init({
      link: elgg.get_site_url() + page.cookiePolicy,
      link2: elgg.get_site_url() + page.legalConditions
    });
    navbar = $('.foowd-navbar');
    navbarBottom = navbar.offset().top + navbar.height();
    $('.elgg-system-messages').css({
      'top': navbarBottom + 'px',
      'display': 'block'
    });
    $('.elgg-system-messages li.elgg-message').finish().fadeIn(0).delay(3000).fadeOut(4000);
    root.removeSystemErrorPopup = function() {
      return $('.elgg-system-messages li.elgg-state-error').finish().fadeIn(0).delay(3000).fadeOut(1000, function() {
        return $(this).remove();
      });
    };
    root.foowdAlert = function(output_msg, title_msg) {
      if (!title_msg) {
        title_msg = 'Alert';
      }
      if (!output_msg) {
        output_msg = 'No Message to Display.';
      }
      return $("<div></div>").html(output_msg).dialog({
        title: title_msg,
        resizable: false,
        modal: true,
        buttons: {
          "Ok": function() {
            return $(this).dialog("close");
          }
        }
      });
    };
  });

}).call(this);
