// Generated by CoffeeScript 1.9.3
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    return define(['elgg', 'jquery', 'crop', 'foowd_utenti/file', 'foowdCropLightbox', 'foowd_utenti/file'], factory);
  } else if (typeof exports === 'object') {
    return module.exports = factory();
  } else {
    return root.returnExports = factory();
  }
})(this, function() {
  var $, Jform, Jhook, crop, elgg, file;
  elgg = require('elgg');
  $ = require('jquery');
  crop = require('foowdCropLightbox');
  Jhook = $('#offer-hook');
  Jform = Jhook.parents('form:first');
  Jform.attr('enctype', 'multipart/form-data');
  file = require('foowd_utenti/file');
  crop.create().initialize(file.fileCropInit());
  $(document).on("foowd:update:file", function(e, mydata) {
    crop.create().initialize(file.fileCropInit());
  });
  return $('form.elgg-form-avatar').submit(function(e) {
    alert('lol');
    e.preventDefault();
    return true;
  });
});
