// Generated by CoffeeScript 1.9.3
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    return define(['jquery'], factory);
  } else if (typeof exports === 'object') {
    return module.exports = factory();
  } else {
    return root.returnExports = factory();
  }
})(this, function() {
  var $, addFile, atLeastOne, fileCropInit, fileField, initCrop;
  $ = require('jquery');
  fileField = function(num) {
    var Jrefr, content;
    Jrefr = $('label[for="Description"]').parent();
    content = $('#fileTmpl').html();
    Jrefr.append(content.replace(/-num_par/g, num));
  };
  addFile = function() {
    var ar, check, m;
    ar = [];
    check = [];
    $('#offer-hook input[type="file"]').each(function() {
      var n, v;
      v = $(this).val();
      n = $(this).attr('data-num');
      if (v === '') {
        $('#file' + n + '-hook').remove();
        return true;
      }
      if (n === '-num_par') {
        return true;
      }
      return ar.push(n);
    });
    m = Math.max.apply(Math, ar);
    if (!isFinite(m)) {
      m = 0;
    }
    m++;
    fileField(m);
    return m;
  };
  fileCropInit = function() {
    var n;
    n = addFile();
    return initCrop(n);
  };
  initCrop = function(n) {
    return {
      urlF: document.getElementById('url').href,
      fileInput: '[name="file' + n + '"]',
      css: ['mod/foowd_utility/js/imgareaselect/css/imgareaselect-default.css', 'mod/foowd_utility/js/foowd-crop/foowd-crop.css'],
      loadedImgContainer: '#file' + n + '-container',
      sourceImg: '#file' + n + '-sorgente',
      imgContainer: '#file' + n + '-image-container',
      imgAreaPrefix: 'file' + n
    };
  };
  atLeastOne = function() {
    var check;
    check = false;
    $('input[type="file"]').each(function() {
      var n, v;
      v = $(this).val();
      n = $(this).attr('name');
      if (v !== '') {
        return check = true;
      }
    });
    return check;
  };
  return {
    atLeastOne: atLeastOne,
    fileCropInit: fileCropInit
  };
});


/*
<!-- <div id="fileTmpl" style="display:">
<div id="file_par-hook">
    <div>
        <label for="file_par">Carica l'immagine *</label><div style="color:red"></div><br>
        <input name="file_par" value="" class="elgg-input-file" type="file">
    </div>
    <center>
        <div id="file_par-container"></div>
    </center>
    <div class="crop">
            <input name="crop_file_par[x1]" value="" type="hidden">
            <input name="crop_file_par[y1]" value="" type="hidden">
            <input name="crop_file_par[x2]" value="" type="hidden">
            <input name="crop_file_par[y2]" value="" type="hidden">    
    </div>
</div>
</div> -->
 */
