// Generated by CoffeeScript 1.9.3
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    return define(['elgg', 'page', 'jquery', 'foowd_utenti/gallery-crop-lightbox', 'foowd_utenti/file'], factory);
  } else if (typeof exports === 'object') {
    return module.exports = factory();
  } else {
    return root.returnExports = factory();
  }
})(this, function() {
  var $, crop, extra, file, makeCrop, par, template;
  $ = require('jquery');
  crop = require('foowd_utenti/gallery-crop-lightbox');
  file = require('foowd_utenti/file');
  $('.elgg-page-topbar').css({
    "z-index": "1"
  });
  par = {
    "urlF": document.getElementById('url').href,
    "guid": $('.guid').attr('data-num')
  };
  extra = {
    "formData": {
      "guid": par.guid,
      "action": "saveFile"
    }
  };
  crop.create().initialize($.extend(file.fileCropInit(), extra));
  template = function(obj) {
    var content;
    if (this.Id == null) {
      this.Id = 0;
    }
    if (!obj.id) {
      this.Id++;
      obj.id = this.Id;
    }
    content = $('#imgTmpl').html();
    content = content.replace(/_imgSource/g, obj.src);
    content = content.replace(/_imgOriginal/g, obj.original);
    content = content.replace(/_imgHost/g, obj.host);
    content = content.replace(/_imgId/g, obj.id);
    return content;
  };
  $(document).on("foowd:lightbox:close", function(e, mydata) {
    var Jimg, send;
    if (mydata.action === 'add') {
      send = $.extend({
        "src": mydata.targetFile
      }, mydata.crop);
      send.action = 'cropFile';
      send.useReturned = function(ret) {
        var content;
        content = template(ret);
        return $('#gallery-container').append(content);
      };
      mydata.Jbox.parent().parent().remove();
      mydata.send = send;
      makeCrop(mydata);
      crop.create().initialize($.extend(file.fileCropInit(), extra));
    }
    if (mydata.action === 'update') {
      Jimg = $(mydata.imgSelector);
      send = mydata.crop;
      send.action = 'updateFile';
      send.src = Jimg.attr('data-original');
      send.useReturned = function(ret) {
        var d, src;
        if (ret.response) {
          d = new Date();
          src = Jimg.attr('src');
          Jimg.attr("src", src + '?' + d.getTime());
        }
      };
      mydata.send = send;
      makeCrop(mydata);
    }
  });
  makeCrop = function(obj) {
    var callback;
    callback = obj.send.useReturned;
    delete obj.send.useReturned;
    return $.ajax({
      method: "GET",
      url: par.urlF,
      data: obj.send,
      success: function(data) {
        var ret;
        data = JSON.parse(data);
        if (data.response) {
          ret = {
            src: obj.profileHost + obj.dirName + '/medium/' + obj.name,
            original: obj.targetFile,
            host: obj.profileHost + obj.dirName + '/' + obj.name,
            response: true
          };
          return callback(ret);
        }
      }
    });
  };
  $('#gallery-container').on('mouseover', '.single', function() {
    return $(this).find('a').css({
      "display": "block"
    });
  });
  $('#gallery-container').on('mouseleave', '.single', function() {
    return $(this).find('a').css({
      "display": "none"
    });
  });
  $('#gallery-container').on('click', '.delete', function() {
    var box, dat, original;
    original = $(this).siblings('img').attr('data-original');
    box = $(this).parent();
    dat = {
      'src': original,
      action: 'removeDir',
      subdir: 'profile',
      guid: par.guid
    };
    return $.ajax({
      method: "GET",
      url: par.urlF,
      data: dat,
      success: function(data) {
        data = JSON.parse(data);
        if (data.response) {
          return box.remove();
        }
      }
    });
  });
  $('#gallery-container').on("click", '.single .change', function(e) {
    var Jimg, selector, sourceImg;
    Jimg = $(this).siblings('img').first();
    selector = Jimg.attr('data-id');
    sourceImg = '[data-id="' + selector + '"]';
    $(document).trigger('foowd:load:img', {
      "imgSelector": sourceImg
    });
  });
  return $(window).on('load', function() {
    return $('.hook').each(function() {
      var Jel, content, obj;
      Jel = $(this);
      obj = {
        src: Jel.attr('data-src'),
        original: Jel.attr('data-original'),
        host: Jel.attr('data-host')
      };
      content = template(obj);
      $('#gallery-container').append(content);
      return $(this).remove();
    });
  });
});
